name: ml-practice-env
channels:
- conda-forge
dependencies:
- python=3.9
- pip
- ipykernel
- pip:
  - pandas==1.4.2
  - numpy==1.22.4
  - matplotlib==3.5.2
  - seaborn==0.11.2
  - mlflow==1.26.1
  - scikit-learn==1.1.1